<?PHP
    
    use App\Controller\Sessions;
    
    $sessao = new Sessions();
    $sessao->start();
    $user = $sessao->getValue('USER');
    
    if(isset($_GET['acao']) && isset($_GET['acao'])=='sair')
    {
        $sessao->deleteValue('USER');
        $sessao->destroy();   
    }
    if(!$sessao->getValue('USER'))
    { 
        echo'<script>window.location="http://localhost/fabrica/";</script>';
        end();
    }
       
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        
        <title>Create new user</title>
        <link rel="stylesheet" type="text/css" href="css/styles.css">
        <style>
            table, td, th {
                border: 1px solid black;
            }

            table {
                border-collapse: collapse;
                width: 100%;
            }

            th {
                height: 50px;
                background-color: #ccc;
            }
            .body{
                width: 50%;
                padding: 10px 10px 10px 10px;
                border: 1px #ccc solid; 
                border-radius: 8px 8px 8px 8px;
                margin: auto;
                    
            }
            .header{
                width: 100%;
                padding-top: 50px;
                text-align: center;
                text-transform: uppercase;
                
            }
            .form-control{
                width: 96%;
                padding:10px;
                margin-bottom: 10px;
            }
            .form-button{
                width: 100%;
                padding: 10px;
                margin-bottom: 10px;
                border-style: none;
                text-transform: uppercase;
                
            }
        </style> 
    </head>
    <body>
        <header class="header">
            <h1>Admin area</h1>
            <?php 
             echo'<h3> Hi! '.ucfirst($user).' <a href="?acao=sair">Logout</a></h3>';
            ?>
            
        </header>
        
        <main>
            
            <div class="body">
                <h3>Edit data of user</h3>
               <?php
                foreach($data as $person)
                {
               ?> 
               <form method="post" action="http://localhost/fabrica/edit-user">
                   <input type="hidden" name="id" class="form-control" value="<?php echo $person->id?>">
                   <input type="text" name="fname" class="form-control" value="<?php echo $person->f_name?>" placeholder="Firt name">
                   <input type="text" name="lname" class="form-control" value="<?php echo $person->l_name?>" placeholder="Last name">
                   <button class="form-button">Edit</button>
               </form>
               <?php
                }
               ?>
            </div>
            
        </main>
        
        <footer>
        </footer>
    </body>
</html>