<?PHP
    
    use App\Controller\Sessions;
    
    $sessao = new Sessions();
    $sessao->start();
    $user = $sessao->getValue('USER');
    
    if(isset($_GET['acao']) && isset($_GET['acao'])=='sair')
    {
        $sessao->deleteValue('USER');
        $sessao->destroy();   
    }
    if(!$sessao->getValue('USER'))
    { 
        echo'<script>window.location="http://localhost/fabrica/";</script>';
        end();
    }
       
?>
<!DOCTYPE html>
<html lang="en">
  <title>Fabrica</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="http://localhost/fabrica/users">Admin-panel</a>
          </div>
          <ul class="nav navbar-nav">

            <li class="dropdown active">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Menu
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="http://localhost/fabrica/list">Show users</a></li>
                <li><a href="http://localhost/fabrica/new-user">Create new user</a></li>
                <li><a href="http://localhost/fabrica/import">Import users</a></li>
                <li><a href="http://localhost/fabrica/export">Export users</a></li>
              </ul>
            </li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span> <?php echo ucfirst($user)?><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="?acao=sair"><span class="glyphicon glyphicon-log-in"></span> Logout </a></li>
                </ul>
            </li>
          </ul>
        </div>
    </nav>
    
    <!--End of nav-->
    
    <div class="container-fluid">
        
        <div style="padding-top:50px"></div>
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <div style="text-align:center"><h2>All users</h2></div>
                    <table class="table">
                                <tr class="active">
                                        <th>#</th>
                                        <th>First name</th>
                                        <th>Last name</th>
                                        <th>Actions</th>
                                </tr>
                    </table>
                <div style="overflow-y: auto; height: 400px">
                    <table class="table">
                                <?PHP
                                foreach ($data as $person)
                                {
                                    echo'<tr><td>'.$person->id.'</td><td>'.utf8_decode($person->f_name).'</td><td>'.utf8_encode($person->l_name).'</td><td><a href="http://localhost/fabrica/edit/'.$person->id.'" title="Edit"><span class="glyphicon glyphicon-pencil"></span></a> <a href="http://localhost/fabrica/delete/'.$person->id.'" title="Delete"><span class="glyphicon glyphicon-trash"></a> </td></tr>';
                                }
                                ?>

                        
                    
                    </table>
                </div>
            </div>
            <div class="col-sm-2"></div>
        </div>
        
    </div>
        
</body>
</html>
            
           