<?PHP
    
    use App\Controller\Sessions;
    
    $sessao = new Sessions();
    $sessao->start();
    $user = $sessao->getValue('USER');
    
    if(isset($_GET['acao']) && isset($_GET['acao'])=='sair')
    {
        $sessao->deleteValue('USER');
        $sessao->destroy();   
    }
    if(!$sessao->getValue('USER'))
    { 
        echo'<script>window.location="http://localhost/fabrica/";</script>';
        end();
    }
       
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        
        <title>Create new user</title>
        <link rel="stylesheet" type="text/css" href="css/styles.css">
         
    </head>
    <body>
        <header>
            <h1>Admin area</h1>
            <?php 
             echo'<h3> Hi! '.ucfirst($user).' <a href="?acao=sair">Logout</a></h3>';
            ?>
            
        </header>
        
        <main>
            <h3>Create new user</h3>
            <div class="body">
               <form method="post" action="http://localhost/fabrica/create">
                   <input type="text" name="fname" class="form-control" placeholder="Firt name">
                   <input type="text" name="lname" class="form-control" placeholder="Last name">
                   <button class="form-button">Create</button>
               </form>
               <span class="error">
               
               </span>
            </div>
            
        </main>
        
        <footer>
        </footer>
    </body>
</html>