<?PHP
    
    use App\Controller\Sessions;
    
    $sessao = new Sessions();
    $sessao->start();
    $user = $sessao->getValue('USER');
    
    if(isset($_GET['acao']) && isset($_GET['acao'])=='sair')
    {
        $sessao->deleteValue('USER');
        $sessao->destroy();   
    }
    if(!$sessao->getValue('USER'))
    { 
        echo'<script>window.location="http://localhost/fabrica/";</script>';
        end();
    }
       
?>
<!DOCTYPE html>
<html lang="en">
  <title>Fabrica</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="http://localhost/fabrica/users">Admin-panel</a>
          </div>
          <ul class="nav navbar-nav">

            <li class="dropdown active">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Menu
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="http://localhost/fabrica/list">Show users</a></li>
                <li><a href="http://localhost/fabrica/new-user">Create new user</a></li>
                <li><a href="#">Import users</a></li>
                <li><a href="#">Export users</a></li>
              </ul>
            </li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><span class="glyphicon glyphicon-user"></span> <?php echo ucfirst($user)?></a></li>
            <li><a href="?acao=sair"><span class="glyphicon glyphicon-log-in"></span> Logout </a></li>
          </ul>
        </div>
    </nav>
    
    <!--End of nav-->
    
    <div class="container-fluid">
        
        <div style="padding-top:100px"></div>
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4">
                <div class="panel" style="border:#ccc 1px solid">
                    <div class="panel-heading" style="text-align:center"><h2>Welcome to admin</h2></div>
                    <div class="panel-body">
                        This is your admin area. Here you can a lot of things about your responsabilites. Enjoy your job.
                    </div>
                </div>
            </div>
            <div class="col-sm-4"></div>
        </div>
        
    </div>
        
</body>
</html>